Repository AY2223S1-CS2103T-W11-4/tp, pull requests merged in 2022-10, with the labels that each got.

#10 Update AbousUs.md
  docs/AboutUs.md
  docs/team/ningtan11.md
Labels: type.Task

#12 Update about us
  docs/AboutUs.md
Labels: priority.High, type.Task

#13 Update README and index
  README.md
  docs/index.md
Labels: priority.High, type.Task

#14 Update cfsy ppp
  docs/team/cfsy.md
Labels: priority.High, type.Task

#15 Update CI link
  README.md
  docs/index.md
Labels: priority.High, type.Task

#16 User guide
  docs/UserGuide.md
Labels: priority.High, type.Task

#17 Dev guide
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: priority.High, type.Task

#49 Add edit item command
  build.gradle
  src/main/java/seedu/waddle/logic/commands/DeleteCommand.java
  src/main/java/seedu/waddle/logic/commands/EditItemCommand.java
  src/main/java/seedu/waddle/logic/parser/EditItemCommandParser.java
  src/main/java/seedu/waddle/logic/parser/WaddleParser.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
Labels: priority.High, type.Story

#51 Add use cases to DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#52 Fix minor bug with error message on add item usage
  src/main/java/seedu/waddle/logic/parser/AddItemCommandParser.java
Labels: bug, priority.Low

#61 Add item priority
  src/main/java/seedu/waddle/logic/commands/AddItemCommand.java
  src/main/java/seedu/waddle/logic/commands/EditItemCommand.java
  src/main/java/seedu/waddle/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/waddle/logic/parser/CliSyntax.java
  src/main/java/seedu/waddle/logic/parser/ParserUtil.java
  src/main/java/seedu/waddle/model/item/Item.java
  src/main/java/seedu/waddle/model/item/Priority.java
  src/main/java/seedu/waddle/storage/JsonAdaptedItem.java
  src/main/java/seedu/waddle/storage/JsonWaddleStorage.java
Labels: priority.High, type.Task

#62 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.Medium, type.Task

#67 Add 'Unplan scheduled item' proposal
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
  src/test/java/seedu/waddle/logic/commands/exceptions/CommandException.java
Labels: documentation

#73 Add new class ItemContainer
  src/main/java/seedu/waddle/model/item/ItemContainer.java
  src/main/java/seedu/waddle/model/item/Priority.java
  src/main/java/seedu/waddle/model/item/UniqueItemList.java
Labels: priority.Medium

#76 Add MultiIndex class
  src/main/java/seedu/waddle/commons/core/index/MultiIndex.java
Labels: priority.High

#77 Change itinerary
  src/main/java/seedu/waddle/commons/core/index/MultiIndex.java
  src/main/java/seedu/waddle/model/item/Cost.java
  src/main/java/seedu/waddle/model/itinerary/Budget.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
Labels: priority.Medium

#78 Day
  src/main/java/seedu/waddle/commons/core/Messages.java
  src/main/java/seedu/waddle/model/item/Day.java
  src/main/java/seedu/waddle/model/item/Duration.java
  src/main/java/seedu/waddle/model/item/Item.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
Labels: priority.Medium, type.Task

#79 Add StartTime class
  src/main/java/seedu/waddle/logic/commands/EditItemCommand.java
  src/main/java/seedu/waddle/logic/parser/CliSyntax.java
  src/main/java/seedu/waddle/logic/parser/EditItemCommandParser.java
  src/main/java/seedu/waddle/logic/parser/ParserUtil.java
  src/main/java/seedu/waddle/model/item/StartTime.java
Labels: priority.Medium, type.Task

#80 Select command
  src/main/java/seedu/waddle/logic/commands/SelectCommand.java
  src/main/java/seedu/waddle/logic/parser/PlanCommandParser.java
  src/main/java/seedu/waddle/logic/parser/WaddleParser.java
  src/main/resources/view/ItineraryListCard.fxml
Labels: priority.Medium, type.Task

#81 Add itinerary methods
  src/main/java/seedu/waddle/commons/core/index/MultiIndex.java
  src/main/java/seedu/waddle/model/item/Day.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
Labels: priority.Medium

#82 Edit commands
  src/main/java/seedu/waddle/commons/core/index/MultiIndex.java
  src/main/java/seedu/waddle/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/waddle/logic/commands/EditCommand.java
  src/main/java/seedu/waddle/logic/commands/EditItemCommand.java
  src/main/java/seedu/waddle/logic/parser/DeleteItemCommandParser.java
  src/main/java/seedu/waddle/logic/parser/EditItemCommandParser.java
  src/main/java/seedu/waddle/logic/parser/ParserUtil.java
  src/main/java/seedu/waddle/model/item/Day.java
  src/main/java/seedu/waddle/model/itinerary/Budget.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
Labels: priority.High

#83 Add basic UI for itinerary page
  src/main/java/seedu/waddle/model/item/Day.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
  src/main/java/seedu/waddle/storage/JsonAdaptedItem.java
  src/main/java/seedu/waddle/ui/ItemGroupCard.java
  src/main/java/seedu/waddle/ui/ItemGroupListPanel.java
  src/main/java/seedu/waddle/ui/ItemListPanel.java
  src/main/java/seedu/waddle/ui/MainWindow.java
  src/main/java/seedu/waddle/ui/UiSizes.java
  src/main/resources/view/ItemGroupListCard.fxml
  src/main/resources/view/ItemGroupListPanel.fxml
  src/main/resources/view/ItemListCard.fxml
Labels: priority.Medium, type.Story

#84 Fix MultiIndex class
  src/main/java/seedu/waddle/commons/core/index/MultiIndex.java
Labels: bug, priority.High

#85 Add plan command
  src/main/java/seedu/waddle/logic/commands/EditItemCommand.java
  src/main/java/seedu/waddle/logic/commands/PlanCommand.java
  src/main/java/seedu/waddle/logic/parser/CliSyntax.java
  src/main/java/seedu/waddle/logic/parser/ParserUtil.java
  src/main/java/seedu/waddle/logic/parser/PlanCommandParser.java
  src/main/java/seedu/waddle/logic/parser/SelectCommandParser.java
  src/main/java/seedu/waddle/logic/parser/WaddleParser.java
  src/main/java/seedu/waddle/model/item/Cost.java
  src/main/java/seedu/waddle/model/itinerary/DayNumber.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
  src/main/java/seedu/waddle/model/itinerary/People.java
Labels: priority.Medium, type.Story

#87 Add unplan command
  src/main/java/seedu/waddle/commons/core/index/MultiIndex.java
  src/main/java/seedu/waddle/logic/commands/PlanCommand.java
  src/main/java/seedu/waddle/logic/commands/UnplanCommand.java
  src/main/java/seedu/waddle/logic/parser/ParserUtil.java
  src/main/java/seedu/waddle/logic/parser/UnplanCommandParser.java
  src/main/java/seedu/waddle/logic/parser/WaddleParser.java
  src/main/java/seedu/waddle/model/itinerary/DayNumber.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
Labels: priority.Medium, type.Story

#88 Fix delete item command and item conflict logic
  src/main/java/seedu/waddle/commons/core/index/MultiIndex.java
  src/main/java/seedu/waddle/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/waddle/logic/parser/ParserUtil.java
  src/main/java/seedu/waddle/model/item/Day.java
Labels: bug

#103 Free command
  src/main/java/seedu/waddle/commons/core/Messages.java
  src/main/java/seedu/waddle/logic/commands/FreeCommand.java
  src/main/java/seedu/waddle/logic/parser/WaddleParser.java
  src/main/java/seedu/waddle/model/item/Day.java
  src/main/java/seedu/waddle/model/item/Item.java
  src/main/java/seedu/waddle/model/item/exceptions/Period.java
  src/main/java/seedu/waddle/model/itinerary/Itinerary.java
  src/main/resources/view/DarkTheme.css
Labels: priority.Medium, type.Story

#107 Dg
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ItineraryClassDiagram.puml
  docs/diagrams/PlanSequenceDiagram.puml
  docs/diagrams/PlanSequenceDiagram2.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/waddle/model/item/Day.java
Labels: priority.High, type.Task

#109 Add diagram pngs
  docs/images/ArchitectureDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ItineraryClassDiagram.png
  docs/images/PlanSequenceDiagram.png
  docs/images/PlanSequenceDiagram2.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Task

#117 Update user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/findTripResult.png
  docs/images/helpMessage.png
Labels: documentation, priority.Low

#119 Fix UserGuide.md broken hyperlinks
  docs/UserGuide.md
Labels: bug, documentation

#131 Fix pdf export diretory to Documents/Waddle
  build.gradle
  src/main/java/seedu/waddle/logic/PdfFiller.java
  src/main/java/seedu/waddle/logic/commands/ExportPdfCommand.java
Labels: bug
